version: '3.9'

services:
  app:
    build: .
    container_name: ${APPNAME}-${VERSION}
    image: ${APPNAME}:${VERSION}
    command: uvicorn main:app --host 0.0.0.0
    env_file:
      - ./.env
    ports:
      - '8004:8000'
    volumes:
      - ./logs:/app/logs
